const datoa = [
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 68,
        "NombreMaquina": "MP01",
        "MinutosTurno": "480.0",
        "TiempoAbajo": 80,
        "TiempoArriba": "400.0",
        "ParosMaquinaTurno": 3,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 68,
        "NombreMaquina": "MP01",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 20,
        "TiempoArriba": "430.0",
        "ParosMaquinaTurno": 1,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 68,
        "NombreMaquina": "MP01",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 20,
        "TiempoArriba": "490.0",
        "ParosMaquinaTurno": 2,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 69,
        "NombreMaquina": "MP03",
        "MinutosTurno": "330.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "330.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 69,
        "NombreMaquina": "MP03",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 39,
        "TiempoArriba": "411.0",
        "ParosMaquinaTurno": 5,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 69,
        "NombreMaquina": "MP03",
        "MinutosTurno": "90.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "90.0",
        "ParosMaquinaTurno": 1,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 72,
        "NombreMaquina": "MP11",
        "MinutosTurno": "378.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "378.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 72,
        "NombreMaquina": "MP11",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 35,
        "TiempoArriba": "415.0",
        "ParosMaquinaTurno": 3,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 72,
        "NombreMaquina": "MP11",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "510.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 73,
        "NombreMaquina": "MP13",
        "MinutosTurno": null,
        "TiempoAbajo": 477,
        "TiempoArriba": null,
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 73,
        "NombreMaquina": "MP13",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 449,
        "TiempoArriba": "1.0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 73,
        "NombreMaquina": "MP13",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 509,
        "TiempoArriba": "1.0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 74,
        "NombreMaquina": "MP14",
        "MinutosTurno": ".0",
        "TiempoAbajo": 0,
        "TiempoArriba": ".0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 74,
        "NombreMaquina": "MP14",
        "MinutosTurno": ".0",
        "TiempoAbajo": 0,
        "TiempoArriba": ".0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 74,
        "NombreMaquina": "MP14",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 238,
        "TiempoArriba": "272.0",
        "ParosMaquinaTurno": 21,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 77,
        "NombreMaquina": "MP15",
        "MinutosTurno": "480.0",
        "TiempoAbajo": 2,
        "TiempoArriba": "478.0",
        "ParosMaquinaTurno": 1,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 77,
        "NombreMaquina": "MP15",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 3,
        "TiempoArriba": "447.0",
        "ParosMaquinaTurno": 1,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 77,
        "NombreMaquina": "MP15",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 9,
        "TiempoArriba": "501.0",
        "ParosMaquinaTurno": 3,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 137,
        "NombreMaquina": "MP16",
        "MinutosTurno": ".0",
        "TiempoAbajo": 0,
        "TiempoArriba": ".0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 137,
        "NombreMaquina": "MP16",
        "MinutosTurno": null,
        "TiempoAbajo": 449,
        "TiempoArriba": null,
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 137,
        "NombreMaquina": "MP16",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 510,
        "TiempoArriba": ".0",
        "ParosMaquinaTurno": 0,
        "Origen": "CON_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 1,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 138,
        "NombreMaquina": "N1",
        "MinutosTurno": "480.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "480.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 2,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 138,
        "NombreMaquina": "N1",
        "MinutosTurno": "450.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "450.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    },
    {
        "Fecha": "2026-08-01",
        "Turno": 3,
        "NoDepto": 24,
        "NombreDepto": "Protecci\u00f3n femenina",
        "NoMaquina": 138,
        "NombreMaquina": "N1",
        "MinutosTurno": "510.0",
        "TiempoAbajo": 0,
        "TiempoArriba": "510.0",
        "ParosMaquinaTurno": 0,
        "Origen": "SIN_RED"
    }
]