<?php
define('UPLOAD_DIR', __DIR__ . '/uploads/');
DEFINE('CSV_FILE', UPLOAD_DIR . 'SALDO_DE_VACACIONES_PLANTA_CUAUTITLAN.csv');
DEFINE('CSV_FILE_SIND', UPLOAD_DIR . 'SINDICALIZADO_CON_LA_RELACION_DE_LOS_SUPERVISORES.csv');
define('ALLOWED_EXT', ['csv']);
// Limite de tamaño de archivo permitido para la carga, en este caso 5MB
define('MAX_FILE_SIZE', 5 * 1024 * 1024);

// Ajustes de nombres segun los encabezadosdel archivo
define('COL_IBM', 'IBM');
define('COL_NOMBRE', 'NOMBRE');
define('COL_FINGRESO', 'F. INGRESO');
define('COL_TIPO', 'TIPO');
define('COL_VAC', 'VAC');

// Nombres para CVS de caso SINDICALIZADOS
define('COL_IBM_SIND', 'IBM');
define('COL_NOMBRE_SIND', 'NOMBRE');
define('COL_PUESTO_SIND', 'PUESTO');
define('COL_IBM_DEL_SUPERVISOR1_SIND', 'IBM DEL SUPERVISOR1');
define('COL_NOMBRE_DEL_SUPERVISOR1_SIND', 'NOMBRE DEL SUPERVISOR1');
define('COL_IBM_DEL_SUPERVISOR2_SIND', 'IBM DEL SUPERVISOR2');
define('COL_NOMBRE_DEL_SUPERVISOR2_SIND', 'NOMBRE DEL SUPERVISOR2');
define('COL_IBM_DEL_SUPERVISOR3_SIND', 'IBM DEL SUPERVISOR3');
define('COL_NOMBRE_DEL_SUPERVISOR3_SIND', 'NOMBRE DEL SUPERVISOR3');
define('COL_IBM_DEL_SUPERVISOR4_SIND', 'IBM DEL SUPERVISOR4');
define('COL_NOMBRE_DEL_SUPERVISOR4_SIND', 'NOMBRE DEL SUPERVISOR4');
define('COL_IBM_DEL_SUPERVISOR5_SIND', 'IBM DEL SUPERVISOR5');
define('COL_NOMBRE_DEL_SUPERVISOR5_SIND', 'NOMBRE DEL SUPERVISOR5');
define('COL_IBM_DEL_SUPERVISOR6_SIND', 'IBM DEL SUPERVISOR6');
define('COL_NOMBRE_DEL_SUPERVISOR6_SIND', 'NOMBRE DEL SUPERVISOR6');

// Separador de csv
define('CSV_SEPARATOR', ',');
?>