var data =  {
    "60": [
        {
            "id": 6579,
            "Fecha": "2026-03-01",
            "Turno": 1,
            "NoMaquina": 60,
            "NombreMaquina": "BCM4",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": 8,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        },
        {
            "id": 6594,
            "Fecha": "2026-03-01",
            "Turno": 2,
            "NoMaquina": 60,
            "NombreMaquina": "BCM4",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": null,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        },
        {
            "id": 6608,
            "Fecha": "2026-03-01",
            "Turno": 3,
            "NoMaquina": 60,
            "NombreMaquina": "BCM4",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": 8.5,
            "MermaPorc": 77,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        }
    ],
    "61": [
        {
            "id": 6580,
            "Fecha": "2026-03-01",
            "Turno": 1,
            "NoMaquina": 61,
            "NombreMaquina": "BCM3",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 328454,
            "Rechazos": 3115,
            "TiempoAbajo": 36,
            "HorasTrabajadas": 5.5,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 36,
            "TotalPiezas": 324288
        },
        {
            "id": 6595,
            "Fecha": "2026-03-01",
            "Turno": 2,
            "NoMaquina": 61,
            "NombreMaquina": "BCM3",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 471730,
            "Rechazos": 2864,
            "TiempoAbajo": 2,
            "HorasTrabajadas": 7.5,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 2,
            "TotalPiezas": 467984
        },
        {
            "id": 6611,
            "Fecha": "2026-03-01",
            "Turno": 3,
            "NoMaquina": 61,
            "NombreMaquina": "BCM3",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 465249,
            "Rechazos": 4323,
            "TiempoAbajo": 14,
            "HorasTrabajadas": 8.5,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 14,
            "TotalPiezas": 459888
        }
    ],
    "62": [
        {
            "id": 6578,
            "Fecha": "2026-03-01",
            "Turno": 1,
            "NoMaquina": 62,
            "NombreMaquina": "PE10",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": null,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        },
        {
            "id": 6609,
            "Fecha": "2026-03-01",
            "Turno": 3,
            "NoMaquina": 62,
            "NombreMaquina": "PE10",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": null,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        }
    ],
    "63": [
        {
            "id": 6618,
            "Fecha": "2026-03-01",
            "Turno": 3,
            "NoMaquina": 63,
            "NombreMaquina": "BCM1",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 0,
            "Rechazos": 0,
            "TiempoAbajo": 100,
            "HorasTrabajadas": 8.5,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 100,
            "TotalPiezas": null
        }
    ],
    "65": [
        {
            "id": 6587,
            "Fecha": "2026-03-01",
            "Turno": 1,
            "NoMaquina": 65,
            "NombreMaquina": "MP25",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 313540,
            "Rechazos": 1827,
            "TiempoAbajo": 31,
            "HorasTrabajadas": 12,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 31,
            "TotalPiezas": 307680
        },
        {
            "id": 6601,
            "Fecha": "2026-03-01",
            "Turno": 2,
            "NoMaquina": 65,
            "NombreMaquina": "MP25",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 535358,
            "Rechazos": 1793,
            "TiempoAbajo": 1,
            "HorasTrabajadas": 15,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 1,
            "TotalPiezas": 531680
        },
        {
            "id": 6616,
            "Fecha": "2026-03-01",
            "Turno": 3,
            "NoMaquina": 65,
            "NombreMaquina": "MP25",
            "NoDepto": 1,
            "NombreDepto": "Pa\u00f1al",
            "Cortes": 545418,
            "Rechazos": 2390,
            "TiempoAbajo": 11,
            "HorasTrabajadas": 17,
            "MermaPorc": 0,
            "TiempoPerdidoPorc": 11,
            "TotalPiezas": 541440
        }
    ]
}