[
  {
    "Fecha": "2026-06-29",
    "Turno": 2,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 12,
    "Etapa": "Azul",
    "Clave": "3302300",
    "Descripcion": "TABBI MOJAVE AZUL 60 GSM 2.25m",
    "MetrosLineales": 79200,
    "MetrosCuadrados": 59.4,
    "Kilogramos": 3240,
    "TiempoAbajo": 65,
    "HorasTrabajadas": "7.5",
    "KGSRechazados": 33,
    "MC": 59.4
  },
  {
    "Fecha": "2026-06-29",
    "Turno": 2,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302302",
    "Descripcion": "TABBI MOJAVE VERDE 60 GSM 2.25m",
    "MetrosLineales": 42600,
    "MetrosCuadrados": 31.95,
    "Kilogramos": 1620,
    "TiempoAbajo": 65,
    "HorasTrabajadas": "7.5",
    "KGSRechazados": 33,
    "MC": 31.95
  },
  {
    "Fecha": "2026-06-29",
    "Turno": 3,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 11,
    "Etapa": "Morado",
    "Clave": "3421927",
    "Descripcion": "TABBI MOJAVE MORADO 77 GSM 2.25m",
    "MetrosLineales": 118200,
    "MetrosCuadrados": 88.65,
    "Kilogramos": 6623,
    "TiempoAbajo": 40,
    "HorasTrabajadas": "8.5",
    "KGSRechazados": 34.2,
    "MC": 88.65
  },
  {
    "Fecha": "2026-07-01",
    "Turno": 1,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302302",
    "Descripcion": "TABBI MOJAVE VERDE 60 GSM 2.25m",
    "MetrosLineales": 120000,
    "MetrosCuadrados": 90,
    "Kilogramos": 5387,
    "TiempoAbajo": 0,
    "HorasTrabajadas": "8.0",
    "KGSRechazados": 26,
    "MC": 90
  },
  {
    "Fecha": "2026-07-01",
    "Turno": 2,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302302",
    "Descripcion": "TABBI MOJAVE VERDE 60 GSM 2.25m",
    "MetrosLineales": 180000,
    "MetrosCuadrados": 135,
    "Kilogramos": 8070,
    "TiempoAbajo": 0,
    "HorasTrabajadas": "7.5",
    "KGSRechazados": null,
    "MC": 135
  },
  {
    "Fecha": "2026-07-01",
    "Turno": 3,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302302",
    "Descripcion": "TABBI MOJAVE VERDE 60 GSM 2.25m",
    "MetrosLineales": 204000,
    "MetrosCuadrados": 153,
    "Kilogramos": 9134,
    "TiempoAbajo": 0,
    "HorasTrabajadas": "8.5",
    "KGSRechazados": null,
    "MC": 153
  },
  {
    "Fecha": "2026-07-02",
    "Turno": 1,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 28,
    "Producto": "Mojave",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302302",
    "Descripcion": "TABBI MOJAVE VERDE 60 GSM 2.25m",
    "MetrosLineales": 20400,
    "MetrosCuadrados": 15.3,
    "Kilogramos": 915,
    "TiempoAbajo": 45,
    "HorasTrabajadas": "8.0",
    "KGSRechazados": 22,
    "MC": 15.3
  },
  {
    "Fecha": "2026-07-02",
    "Turno": 1,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 27,
    "Producto": "Mocassin",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302382",
    "Descripcion": "TABBI MOCCASIN VERDE 47 GSM 2.25m",
    "MetrosLineales": 126000,
    "MetrosCuadrados": 94.5,
    "Kilogramos": 4423,
    "TiempoAbajo": 45,
    "HorasTrabajadas": "8.0",
    "KGSRechazados": 22,
    "MC": 94.5
  },
  {
    "Fecha": "2026-07-02",
    "Turno": 2,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 27,
    "Producto": "Mocassin",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302382",
    "Descripcion": "TABBI MOCCASIN VERDE 47 GSM 2.25m",
    "MetrosLineales": 180000,
    "MetrosCuadrados": 135,
    "Kilogramos": 6340,
    "TiempoAbajo": 30,
    "HorasTrabajadas": "7.5",
    "KGSRechazados": 14,
    "MC": 135
  },
  {
    "Fecha": "2026-07-02",
    "Turno": 3,
    "NoDepto": 2,
    "NombreDepto": "TNT",
    "NoMaquina": 85,
    "NombreMaquina": "TABBI",
    "idCategoria": 14,
    "Categoria": "TABBI",
    "idProducto": 27,
    "Producto": "Mocassin",
    "idEtapa": 10,
    "Etapa": "Verde",
    "Clave": "3302382",
    "Descripcion": "TABBI MOCCASIN VERDE 47 GSM 2.25m",
    "MetrosLineales": 206400,
    "MetrosCuadrados": 154.8,
    "Kilogramos": 7248,
    "TiempoAbajo": 0,
    "HorasTrabajadas": "8.5",
    "KGSRechazados": null,
    "MC": 154.8
  }
]