const data = [ {
        Fecha: "2026-08-14",
        Turno: 2,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: null,
        Categoria: null,
        idProducto: null,
        Producto: null,
        idEtapa: null,
        Etapa: null,
        Clave: null,
        Descripcion: null,
        Reales: null,
        USTD: null,
        AcumuladoUSTD: null,
        Piezas: null,
        TotalPiezas: null,
        Cortes: 0,
        Rechazos: 1,
        TiempoAbajo: 449.98333740234375,
        HorasTrabajadas: null,
      },
      {
        Fecha: "2026-08-18",
        Turno: 1,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: 2,
        Categoria: "Calzón Entrenador",
        idProducto: 8,
        Producto: "Pull-Ups",
        idEtapa: 6,
        Etapa: "Extra Jumbo",
        Clave: "67319",
        Descripcion: "Pull Ups Niño XL Frozen 30's x 4",
        Reales: 825,
        USTD: 660,
        AcumuladoUSTD: 660,
        Piezas: 99000,
        TotalPiezas: 137040,
        Cortes: 145427,
        Rechazos: 8232,
        TiempoAbajo: 0,
        HorasTrabajadas: "4.0",
      },
      {
        Fecha: "2026-08-18",
        Turno: 1,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: 2,
        Categoria: "Calzón Entrenador",
        idProducto: 8,
        Producto: "Pull-Ups",
        idEtapa: 6,
        Etapa: "Extra Jumbo",
        Clave: "66797",
        Descripcion: "Pull Ups Niño XL Frozen 15's x 8",
        Reales: 317,
        USTD: 253.6,
        AcumuladoUSTD: 253.6,
        Piezas: 38040,
        TotalPiezas: 137040,
        Cortes: 0,
        Rechazos: 0,
        TiempoAbajo: 0,
        HorasTrabajadas: ".0",
      },
      {
        Fecha: "2026-08-18",
        Turno: 2,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: 2,
        Categoria: "Calzón Entrenador",
        idProducto: 8,
        Producto: "Pull-Ups",
        idEtapa: 6,
        Etapa: "Extra Jumbo",
        Clave: "67319",
        Descripcion: "Pull Ups Niño XL Frozen 30's x 4",
        Reales: 766,
        USTD: 612.8,
        AcumuladoUSTD: 1272.8,
        Piezas: 91920,
        TotalPiezas: 232920,
        Cortes: 241894,
        Rechazos: 8566,
        TiempoAbajo: 22.66666603088379,
        HorasTrabajadas: "7.5",
      },
      {
        Fecha: "2026-08-18",
        Turno: 2,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: 2,
        Categoria: "Calzón Entrenador",
        idProducto: 8,
        Producto: "Pull-Ups",
        idEtapa: 6,
        Etapa: "Extra Jumbo",
        Clave: "66797",
        Descripcion: "Pull Ups Niño XL Frozen 15's x 8",
        Reales: 1175,
        USTD: 940,
        AcumuladoUSTD: 1193.6,
        Piezas: 141000,
        TotalPiezas: 232920,
        Cortes: 0,
        Rechazos: 0,
        TiempoAbajo: 0,
        HorasTrabajadas: ".0",
      },
      {
        Fecha: "2026-08-18",
        Turno: 3,
        NoDepto: 1,
        NombreDepto: "Pañal",
        NoMaquina: 64,
        NombreMaquina: "MP22",
        idCategoria: 2,
        Categoria: "Calzón Entrenador",
        idProducto: 8,
        Producto: "Pull-Ups",
        idEtapa: 6,
        Etapa: "Extra Jumbo",
        Clave: "67319",
        Descripcion: "Pull Ups Niño XL Frozen 30's x 4",
        Reales: 819,
        USTD: 655.2,
        AcumuladoUSTD: 1928,
        Piezas: 98280,
        TotalPiezas: 252600,
        Cortes: 263826,
        Rechazos: 10876,
        TiempoAbajo: 54.349998474121094,
        HorasTrabajadas: "8.5",
      },]